name: myfirst-github-workflow

run-name: ${{github.actor }} is learning Github Actions

on: [push]

jobs:
  my-custom-jobs:
    runs-on: ubuntu-latest 
    steps:
      -name: echo message step
       run: echo "Hello World"
      -name: display hostname
       run: hostname 